version: "3.8"

services:
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: "babaquero07"
      POSTGRES_PASSWORD: "@KuepaChallenge-123"
      POSTGRES_DB: "kuepa-challenge"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
